[package]
name = "day-5"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.1"

[[bin]]
name = "day-5"
path = "src/main.rs"

[profile.dev]

[profile.release]
debug = 0
opt-level = 3
strip = "debuginfo"
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"

